apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryan-api
  template:
    metadata:
      labels:
        app: ryan-api
    spec:
      containers:
      - name: ryan-api
        # This image is going to be the path to the image you create in a future step
        image: us-docker.pkg.dev/cit262-team-404421/ryan-api/api-tests
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.25"
            memory: "250Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          failureThreshold: 1
          periodSeconds: 10
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 10